from src.core.flow import I


class Cross(I.Cross):
    def to_loader_input(self, output): ...
    def to_data_processor_input(self, output): ...
    def to_model_input(self, output): ...
    def to_evaluator_input(self, output): ...
